name = "ParametricDAQP"
uuid = "19f72acb-e2a9-45c8-96b9-4d5487c8db2e"
authors = ["Daniel Arnstr√∂m <daniel.arnstrom@gmail.com>"]
version = "0.4.2"

[deps]
DAQPBase = "833476c3-a8c0-4073-9b64-6473509843fe"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolyDAQP = "be5c70c9-e47a-4559-82a9-cba980583202"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
DAQPBase = "0.3.0"
PolyDAQP = "0.3.5"
RecipesBase = "1.3.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
